name: Build Plugin

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/icons.yml'
      - 'generate/**'
      - 'pyproject.toml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: sudo chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Plugin
          path: build/distributions/cat-activity-*.zip