name: Python Icons CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - 'generate/**'
      - '.github/workflows/icons.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'generate/**'
      - '.github/workflows/icons.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - run: poetry install

      - name: Run generate.py
        working-directory: ./generate
        run: poetry run python generate.py

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3.4.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./generate/web --project-name=assets
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}